import logo from "./logo.png"
import alexa from "./alexia.png"
import camera from "./camera.png"
import mouse from "./mouse.png"
import phone from "./phone.png"
import station from "./playstation.png"
import watch from "./watch.png"
import automobile from "./automobileF.jpg"
import baby from "./BabyF.jpg"
import electronics from "./Electronics.jpeg" 
import fashion from "./fashionF.jpg"
import health from "./HealthF.webp"
import phoneF from "./phonesF.webp"
import super2F from "./super2F.jpg"
import gaming from "./GamingF.webp"
import babyhat from "./baby-hat.png"
import babyjacket from "./baby-jacket.png"
import basket from "./basket1.png"
import lg1 from "./lg1.png"
import lg2 from "./lg2.png"
import lg3 from "./lg3.png"
import samsung01 from "./samsung01.png"
import samsung2 from "./samsung2.png"
import samsung3 from "./samsung3.png"
import trouser from "./trouser-woman.png"
import trouser1 from "./trouser1.png"
import trouser2 from "./trouser2.png"

export {
    logo,alexa,camera,mouse,phone,station,watch,automobile,baby,electronics,fashion,health,phoneF,super2F,gaming,babyhat,babyjacket,basket,lg1,lg2,lg3,samsung01,samsung2,samsung3,trouser,trouser1,trouser2
};